version: "2"

services:
    api:
        extends:
            file: docker-common.yml
            service: go-rest-api
        ports:
            - 8081:8081
    nginx:
        extends:
            file: docker-common.yml
            service: nginx
        ports:
            - 8000:8000
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - api